# Generated by Django 4.0.3 on 2022-03-30 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_couninstock_product_countinstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='./sample.jpg', null=True, upload_to=''),
        ),
    ]
