# Generated by Django 4.0.3 on 2022-04-04 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_review_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='userName',
            new_name='username',
        ),
    ]
